In [1]:
import numpy as np
from google.colab import files
uploaded = files.upload()

Saving sliced.npy to sliced (1).npy


**(1)** Load the array you saved in the previous lesson from the disk.

In [2]:
sliced = np.load("sliced.npy")
sliced

array([[ 1.    , 36.8578, 44.4161, 16.97  ,  4.    ],
       [ 1.    , 37.4341, 35.852 ,  7.02  ,  4.1   ],
       [ 1.    , 37.6878, 37.4016, 10.27  ,  4.4   ],
       [ 1.    , 37.2003, 30.4376, 78.07  ,  4.    ],
       [ 1.    , 35.6846, 26.7266, 42.77  ,  4.5   ],
       [ 1.    , 36.4171, 28.6991, 14.86  ,  4.1   ],
       [ 1.    , 36.0535, 31.2135, 36.68  ,  5.2   ],
       [ 1.    , 37.1958, 30.6241, 50.33  ,  4.8   ],
       [ 1.    , 36.9653, 27.7633,  6.93  ,  4.3   ],
       [ 1.    , 38.893 , 26.4483, 11.62  ,  4.2   ],
       [ 1.    , 37.3773, 36.3855, 10.53  ,  4.8   ],
       [ 1.    , 35.8861, 26.0695, 28.49  ,  4.9   ],
       [ 1.    , 37.4635, 36.3113, 15.29  ,  4.3   ],
       [ 1.    , 37.0201, 36.0845, 10.    ,  4.1   ],
       [ 1.    , 37.6546, 26.6698,  4.5   ,  4.5   ],
       [ 1.    , 37.5318, 29.848 , 17.58  ,  4.6   ],
       [ 1.    , 39.0388, 44.1533,  7.52  ,  4.5   ],
       [ 1.    , 38.357 , 44.8686, 10.05  ,  4.1   ],
       [ 1.    , 35.7018, 28

**(2)** Display the mean and the standard deviation for each column.

In [3]:
print("Mean: {}".format(np.mean(sliced, axis=0)))
print("Standard Deviation: {}".format(np.std(sliced, axis=0)))

Mean: [ 1.      37.20543 33.27595 19.818    4.38   ]
Standard Deviation: [ 0.          0.92015317  6.07459305 18.28870351  0.33105891]


**(3)** Subtract 1, 25, 25, 10, 4 from columns in order. (Remember it can be subtracted in one line of code.)

In [4]:
sliced - np.broadcast_to([1, 25, 25, 10, 4], (20, 5))

array([[ 0.00000e+00,  1.18578e+01,  1.94161e+01,  6.97000e+00,
         0.00000e+00],
       [ 0.00000e+00,  1.24341e+01,  1.08520e+01, -2.98000e+00,
         1.00000e-01],
       [ 0.00000e+00,  1.26878e+01,  1.24016e+01,  2.70000e-01,
         4.00000e-01],
       [ 0.00000e+00,  1.22003e+01,  5.43760e+00,  6.80700e+01,
         0.00000e+00],
       [ 0.00000e+00,  1.06846e+01,  1.72660e+00,  3.27700e+01,
         5.00000e-01],
       [ 0.00000e+00,  1.14171e+01,  3.69910e+00,  4.86000e+00,
         1.00000e-01],
       [ 0.00000e+00,  1.10535e+01,  6.21350e+00,  2.66800e+01,
         1.20000e+00],
       [ 0.00000e+00,  1.21958e+01,  5.62410e+00,  4.03300e+01,
         8.00000e-01],
       [ 0.00000e+00,  1.19653e+01,  2.76330e+00, -3.07000e+00,
         3.00000e-01],
       [ 0.00000e+00,  1.38930e+01,  1.44830e+00,  1.62000e+00,
         2.00000e-01],
       [ 0.00000e+00,  1.23773e+01,  1.13855e+01,  5.30000e-01,
         8.00000e-01],
       [ 0.00000e+00,  1.08861e+01,  1.0695

**(4)** Multiply each element by 2. (Remember it can be multiplied in one line of code.)

In [5]:
sliced * 2

array([[  2.    ,  73.7156,  88.8322,  33.94  ,   8.    ],
       [  2.    ,  74.8682,  71.704 ,  14.04  ,   8.2   ],
       [  2.    ,  75.3756,  74.8032,  20.54  ,   8.8   ],
       [  2.    ,  74.4006,  60.8752, 156.14  ,   8.    ],
       [  2.    ,  71.3692,  53.4532,  85.54  ,   9.    ],
       [  2.    ,  72.8342,  57.3982,  29.72  ,   8.2   ],
       [  2.    ,  72.107 ,  62.427 ,  73.36  ,  10.4   ],
       [  2.    ,  74.3916,  61.2482, 100.66  ,   9.6   ],
       [  2.    ,  73.9306,  55.5266,  13.86  ,   8.6   ],
       [  2.    ,  77.786 ,  52.8966,  23.24  ,   8.4   ],
       [  2.    ,  74.7546,  72.771 ,  21.06  ,   9.6   ],
       [  2.    ,  71.7722,  52.139 ,  56.98  ,   9.8   ],
       [  2.    ,  74.927 ,  72.6226,  30.58  ,   8.6   ],
       [  2.    ,  74.0402,  72.169 ,  20.    ,   8.2   ],
       [  2.    ,  75.3092,  53.3396,   9.    ,   9.    ],
       [  2.    ,  75.0636,  59.696 ,  35.16  ,   9.2   ],
       [  2.    ,  78.0776,  88.3066,  15.04  ,   9.    